### PR TITLE
Add createProject local documents support

### PR DESCRIPTION
**Pull request by ivanm-gdp**
## Changes

- replaced project.py
- removed samples for v1 flow

<details><summary>Chore: setup v1 v2 branches - DONE!</summary>

## Help needed: 
1. Setup Tag / Releases for v1 - I managed to set [Releases on my fork](https://github.com/ivanm-gdp/api-client-example/releases/tag/v1) by running the following command locally
    ```
    git checkout master
    git tag v1
    git push <personal_remote> --tags
    ```
    and then publishing a new release via Github's UI
2. Create a v1 & v2 protected branch (then, I can merge to that branch instead of master)
This way, while we are still transitioning, others visiting this repo will still see the v1 (master) version
Once the mutation is fully released, we can merge the v2 branch into master, and keep the v1 in a separate branch
</details>

### CODE REVIEW

**Comment by ivanm-gdp** [comment]
wait, reverting to draft

most likely will change approach - separate classes between launch & create
https://github.com/vulcan-ai/vulcan/pull/18929#discussion_r1336836720

**Comment by rikoap** [comment]
@ivanm-gdp No.. gw kalo bedain v1 dan v2 nya itu dari git tags / branch. Jadi di dokumentasi gitbook yg baru kita arahkan untuk clone yg latest versi. Jadi di codenya tetep bersih cuma ada 1 project.py . Gimana No?

**Comment by ivanm-gdp** [comment]
oh okay 👍🏼 
berarti, ini perlu buat tag dulu v1 gt ya

PR **_replace_** project.py dan related files ke createProject

... oh iya, aku ngga ada akses ke org / repo ini untuk buat tag dsb, jadi perlu bantuan sih nantinya

**Comment by rikoap** [comment]
> ... oh iya, aku ngga ada akses ke org / repo ini untuk buat tag dsb, jadi perlu bantuan sih nantinya

Yup, request aja No

> berarti, ini perlu buat tag dulu v1 gt ya
> 
> PR replace project.py dan related files ke createProject

Yup betul....

**Review by michael-jong-ds — APPROVED** [review]
blackbox tested, lgtm

**Pull request merged**
